-- [운영 적용 이력] 2026-07-03 / Supabase Studio SQL Editor 수동 실행 (014 migration 이전)
-- [소스 관리 편입 목적] 데이터 이력 보존 — "미실행 파일" 오인 방지
-- [재실행 안전성] ON CONFLICT (city, name) DO NOTHING → 기존 row 보호.
--               이 파일은 신규 데이터 추가용 템플릿이 아님.
--               014 category normalization 이후 신규 city_spots insert는
--               반드시 표준 category 만 사용할 것:
--               'attraction' / 'restaurant' / 'nature' / 'event' / 'accommodation'
--               이 파일의 비표준 category 값('Beach','Market' 등)을 포함한
--               신규 row는 CHECK constraint(city_spots_category_check) 위반으로 실패함.

BEGIN;

-- 1) 기존 seed city 값 소문자 통일
UPDATE city_spots
SET city = 'busan'
WHERE city = 'Busan';

-- 2) Busan city spots import (batch 1 — 31 spots)
INSERT INTO city_spots
  (city, name, category, district, address, description, why_it_matters,
   image_url, map_url, naver_map_url, lat, lng,
   duration_minutes, best_time_slot, opening_hours, tags,
   solo_friendly, foreign_card_accepted, cash_only, source_type,
   entry_fee, difficulty, official_url, affiliate_url, affiliate_provider)
VALUES
  (
    'busan', 'Haeundae Beach', 'Beach', 'Haeundae-gu',
    'Haeundaehaebyeon-ro, Haeundae-gu, Busan',
    'Busan''s most famous urban beach with hotels, restaurants and night views',
    'Best anchor spot for foreign travelers and beach hotel affiliate conversion',
    'https://source.unsplash.com/1200x800/?busan,haeundae',
    'https://www.google.com/maps/search/?api=1&query=Haeundae+Beach+Busan',
    'https://map.naver.com/p/search/Haeundae%20Beach%20Busan',
    35.1587, 129.1604, 120, 'afternoon', NULL,
    ARRAY['#Beach','#HotelArea','#OceanView','#NightView'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1',
    'booking'
  ),
  (
    'busan', 'Gwangalli Beach', 'Beach', 'Suyeong-gu',
    'Gwanganhaebyeon-ro, Suyeong-gu, Busan',
    'A lively beach facing Gwangan Bridge with cafes bars and night scenery',
    'High value nightlife and accommodation zone for affiliate traffic',
    'https://source.unsplash.com/1200x800/?busan,gwangalli',
    'https://www.google.com/maps/search/?api=1&query=Gwangalli+Beach+Busan',
    'https://map.naver.com/p/search/Gwangalli%20Beach%20Busan',
    35.1532, 129.1187, 120, 'evening', NULL,
    ARRAY['#Beach','#BridgeView','#NightView','#Cafe'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1',
    'booking'
  ),
  (
    'busan', 'Songjeong Beach', 'Beach', 'Haeundae-gu',
    'Songjeong-dong, Haeundae-gu, Busan',
    'A relaxed surf beach popular with young travelers and cafes',
    'Good alternative to Haeundae with surf and stay package potential',
    'https://source.unsplash.com/1200x800/?busan,songjeong',
    'https://www.google.com/maps/search/?api=1&query=Songjeong+Beach+Busan',
    'https://map.naver.com/p/search/Songjeong%20Beach%20Busan',
    35.1786, 129.1997, 120, 'morning', NULL,
    ARRAY['#Beach','#Surfing','#Cafe','#Relaxed'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1',
    'booking'
  ),
  (
    'busan', 'Songdo Beach', 'Beach', 'Seo-gu',
    'Songdohaebyeon-ro, Seo-gu, Busan',
    'Korea''s first public beach with cable car and coastal walk access',
    'Strong paid attraction gateway through cable car and nearby hotels',
    'https://source.unsplash.com/1200x800/?busan,songdo',
    'https://www.google.com/maps/search/?api=1&query=Songdo+Beach+Busan',
    'https://map.naver.com/p/search/Songdo%20Beach%20Busan',
    35.0764, 129.0185, 120, 'afternoon', NULL,
    ARRAY['#Beach','#CableCar','#CoastalWalk','#Family'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1',
    'booking'
  ),
  (
    'busan', 'Dadaepo Beach', 'Beach', 'Saha-gu',
    'Dadae-dong, Saha-gu, Busan',
    'A wide west Busan beach known for sunsets and open tidal scenery',
    'Excellent sunset route for travelers seeking less crowded places',
    'https://source.unsplash.com/1200x800/?busan,sunset',
    'https://www.google.com/maps/search/?api=1&query=Dadaepo+Beach+Busan',
    'https://map.naver.com/p/search/Dadaepo%20Beach%20Busan',
    35.0479, 128.9667, 120, 'sunset', NULL,
    ARRAY['#Beach','#Sunset','#Free','#Local'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1',
    'booking'
  ),
  (
    'busan', 'Gamcheon Culture Village', 'Culture', 'Saha-gu',
    '203 Gamnae 2-ro, Saha-gu, Busan',
    'A colorful hillside village with murals alleys viewpoints and photo zones',
    'One of Busan''s strongest foreign visitor photo and tour conversion spots',
    'https://source.unsplash.com/1200x800/?gamcheon,busan',
    'https://www.google.com/maps/search/?api=1&query=Gamcheon+Culture+Village+Busan',
    'https://map.naver.com/p/search/Gamcheon%20Culture%20Village%20Busan',
    35.0975, 129.0106, 120, 'morning',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#CultureVillage','#PhotoSpot','#Walking','#View'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Jagalchi Market', 'Market', 'Jung-gu',
    '52 Jagalchihaean-ro, Jung-gu, Busan',
    'Busan''s landmark seafood market near Nampo and BIFF Square',
    'High food tour and local experience affiliate value',
    'https://source.unsplash.com/1200x800/?busan,seafood',
    'https://www.google.com/maps/search/?api=1&query=Jagalchi+Market+Busan',
    'https://map.naver.com/p/search/Jagalchi%20Market%20Busan',
    35.0968, 129.0305, 90, 'lunch',
    '{"open":"05:00","close":"22:00"}'::jsonb,
    ARRAY['#Seafood','#Market','#LocalFood','#Nampo'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Gukje Market', 'Market', 'Jung-gu',
    'Gukjesijang 2-gil, Jung-gu, Busan',
    'A large traditional market district with street food goods and alleys',
    'Useful for shopping food tours and Nampo itinerary clustering',
    'https://source.unsplash.com/1200x800/?korea,market',
    'https://www.google.com/maps/search/?api=1&query=Gukje+Market+Busan',
    'https://map.naver.com/p/search/Gukje%20Market%20Busan',
    35.1014, 129.0284, 90, 'afternoon',
    '{"open":"09:00","close":"20:00"}'::jsonb,
    ARRAY['#Market','#StreetFood','#Shopping','#Nampo'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'BIFF Square', 'Culture', 'Jung-gu',
    'BIFF-gwangjang-ro, Jung-gu, Busan',
    'A street culture zone known for film history snacks and night crowds',
    'Good night itinerary connector between markets and hotels',
    'https://source.unsplash.com/1200x800/?busan,streetfood',
    'https://www.google.com/maps/search/?api=1&query=BIFF+Square+Busan',
    'https://map.naver.com/p/search/BIFF%20Square%20Busan',
    35.0982, 129.0291, 60, 'evening', NULL,
    ARRAY['#StreetFood','#Cinema','#Nampo','#NightWalk'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1',
    'booking'
  ),
  (
    'busan', 'Yongdusan Park and Busan Tower', 'Landmark', 'Jung-gu',
    '37-55 Yongdusan-gil, Jung-gu, Busan',
    'A central hill park with Busan Tower and views over the old downtown',
    'Paid observatory plus Nampo hotel and tour conversion potential',
    'https://source.unsplash.com/1200x800/?busan,tower',
    'https://www.google.com/maps/search/?api=1&query=Busan+Tower+Yongdusan+Park',
    'https://map.naver.com/p/search/Busan%20Tower%20Yongdusan%20Park',
    35.1007, 129.0326, 90, 'sunset',
    '{"open":"10:00","close":"22:00"}'::jsonb,
    ARRAY['#Tower','#Viewpoint','#Nampo','#Landmark'],
    true, true, false, 'manual', '₩12,000', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Haedong Yonggungsa Temple', 'Temple', 'Gijang-gun',
    '86 Yonggung-gil, Gijang-gun, Busan',
    'A rare seaside temple built dramatically beside rocks and ocean waves',
    'One of Busan''s highest converting day tour stops for foreign visitors',
    'https://source.unsplash.com/1200x800/?korea,temple,sea',
    'https://www.google.com/maps/search/?api=1&query=Haedong+Yonggungsa+Temple+Busan',
    'https://map.naver.com/p/search/Haedong%20Yonggungsa%20Temple%20Busan',
    35.1883, 129.2233, 90, 'morning',
    '{"open":"04:30","close":"19:00"}'::jsonb,
    ARRAY['#Temple','#OceanView','#Gijang','#PhotoSpot'],
    true, true, false, 'manual', 'Free', NULL,
    'https://english.visitkorea.or.kr',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Beomeosa Temple', 'Temple', 'Geumjeong-gu',
    '250 Beomeosa-ro, Geumjeong-gu, Busan',
    'A historic mountain temple at the foot of Geumjeongsan',
    'Strong culture plus hiking combination for premium itinerary design',
    'https://source.unsplash.com/1200x800/?korea,beomeosa',
    'https://www.google.com/maps/search/?api=1&query=Beomeosa+Temple+Busan',
    'https://map.naver.com/p/search/Beomeosa%20Temple%20Busan',
    35.2838, 129.0686, 120, 'morning',
    '{"open":"08:30","close":"17:30"}'::jsonb,
    ARRAY['#Temple','#Mountain','#History','#Hiking'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.beomeo.kr',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Taejongdae Resort Park', 'Nature', 'Yeongdo-gu',
    '24 Jeonmang-ro, Yeongdo-gu, Busan',
    'A coastal park with cliffs forest lighthouse and ocean views',
    'Essential Busan nature landmark with tour bus and cruise upsell potential',
    'https://source.unsplash.com/1200x800/?busan,cliff',
    'https://www.google.com/maps/search/?api=1&query=Taejongdae+Busan',
    'https://map.naver.com/p/search/Taejongdae%20Busan',
    35.0527, 129.0866, 150, 'afternoon', NULL,
    ARRAY['#CoastalPark','#Cliff','#OceanView','#Lighthouse'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Oryukdo Skywalk', 'Landmark', 'Nam-gu',
    '137 Oryukdo-ro, Nam-gu, Busan',
    'A glass skywalk overlooking Oryukdo Islets and the open sea',
    'Powerful short stop for coastal tours and Igidae trail starts',
    'https://source.unsplash.com/1200x800/?busan,ocean,skywalk',
    'https://www.google.com/maps/search/?api=1&query=Oryukdo+Skywalk+Busan',
    'https://map.naver.com/p/search/Oryukdo%20Skywalk%20Busan',
    35.1004, 129.1226, 45, 'morning',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#Skywalk','#OceanView','#PhotoSpot','#Free'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Igidae Coastal Trail', 'Hiking', 'Nam-gu',
    'Igidae Park, Nam-gu, Busan',
    'A scenic coastal hiking trail linking cliffs forests and sea views',
    'Core urban hiking product with strong foreign traveler appeal',
    'https://source.unsplash.com/1200x800/?busan,coastal,trail',
    'https://www.google.com/maps/search/?api=1&query=Igidae+Coastal+Trail+Busan',
    'https://map.naver.com/p/search/Igidae%20Coastal%20Trail%20Busan',
    35.1294, 129.1197, 150, 'morning', NULL,
    ARRAY['#Hiking','#OceanView','#Cliff','#Free'],
    true, true, false, 'manual', 'Free', 'moderate',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Jangsan Mountain', 'Hiking', 'Haeundae-gu',
    'Jangsan-ro, Haeundae-gu, Busan',
    'A mountain above Haeundae with city ocean and valley views',
    'Best Haeundae-based hiking route for hotel guests and repeat visitors',
    'https://source.unsplash.com/1200x800/?busan,mountain,hiking',
    'https://www.google.com/maps/search/?api=1&query=Jangsan+Mountain+Busan',
    'https://map.naver.com/p/search/Jangsan%20Mountain%20Busan',
    35.1951, 129.1646, 180, 'morning', NULL,
    ARRAY['#Hiking','#MountainView','#Haeundae','#Free'],
    true, true, false, 'manual', 'Free', 'moderate',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Geumjeongsan Mountain', 'Hiking', 'Geumjeong-gu',
    'Geumjeongsan, Geumjeong-gu, Busan',
    'Busan''s major mountain with fortress walls temples and ridge views',
    'High value hiking flagship connecting Beomeosa and Geumgang Park',
    'https://source.unsplash.com/1200x800/?korea,mountain,fortress',
    'https://www.google.com/maps/search/?api=1&query=Geumjeongsan+Mountain+Busan',
    'https://map.naver.com/p/search/Geumjeongsan%20Mountain%20Busan',
    35.2806, 129.0556, 240, 'morning', NULL,
    ARRAY['#Hiking','#Fortress','#Temple','#Mountain'],
    true, true, false, 'manual', 'Free', 'hard',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Geumjeongsanseong Fortress', 'Hiking', 'Geumjeong-gu',
    'Geumseong-dong, Geumjeong-gu, Busan',
    'Historic mountain fortress walls stretching along Geumjeongsan ridges',
    'Combines history and trekking for premium guided hiking content',
    'https://source.unsplash.com/1200x800/?korea,fortress,trail',
    'https://www.google.com/maps/search/?api=1&query=Geumjeongsanseong+Fortress+Busan',
    'https://map.naver.com/p/search/Geumjeongsanseong%20Fortress%20Busan',
    35.2527, 129.0552, 180, 'morning', NULL,
    ARRAY['#Hiking','#Fortress','#History','#View'],
    true, true, false, 'manual', 'Free', 'moderate',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Hwangnyeongsan Mountain Observatory', 'Viewpoint', 'Suyeong-gu',
    'Hwangnyeongsan-ro, Suyeong-gu, Busan',
    'A mountain viewpoint famous for panoramic night views over Busan',
    'Top nightlife and taxi tour conversion spot near Seomyeon and Gwangalli',
    'https://source.unsplash.com/1200x800/?busan,nightview',
    'https://www.google.com/maps/search/?api=1&query=Hwangnyeongsan+Observatory+Busan',
    'https://map.naver.com/p/search/Hwangnyeongsan%20Observatory%20Busan',
    35.1563, 129.0823, 90, 'night', NULL,
    ARRAY['#NightView','#Viewpoint','#Drive','#Romantic'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Baegyangsan Mountain', 'Hiking', 'Busanjin-gu',
    'Baegyangsan, Busanjin-gu, Busan',
    'A central Busan mountain with forest trails and city views',
    'Good local hiking option near Seomyeon for repeat travelers',
    'https://source.unsplash.com/1200x800/?korea,forest,hiking',
    'https://www.google.com/maps/search/?api=1&query=Baegyangsan+Mountain+Busan',
    'https://map.naver.com/p/search/Baegyangsan%20Mountain%20Busan',
    35.1799, 129.0218, 180, 'morning', NULL,
    ARRAY['#Hiking','#Forest','#CityView','#Free'],
    true, true, false, 'manual', 'Free', 'moderate',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Bongnaesan Mountain', 'Hiking', 'Yeongdo-gu',
    'Bongnaesan, Yeongdo-gu, Busan',
    'A Yeongdo mountain offering harbor and island views',
    'Pairs well with Huinnyeoul and Taejongdae for island day routes',
    'https://source.unsplash.com/1200x800/?busan,harbor,mountain',
    'https://www.google.com/maps/search/?api=1&query=Bongnaesan+Mountain+Busan',
    'https://map.naver.com/p/search/Bongnaesan%20Mountain%20Busan',
    35.0745, 129.0641, 150, 'morning', NULL,
    ARRAY['#Hiking','#HarborView','#Yeongdo','#Free'],
    true, true, false, 'manual', 'Free', 'moderate',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Seunghaksan Mountain', 'Hiking', 'Saha-gu',
    'Seunghaksan, Saha-gu, Busan',
    'A west Busan ridge mountain known for reeds and Nakdong River views',
    'Useful for sunset hiking and local nature differentiation',
    'https://source.unsplash.com/1200x800/?korea,reeds,mountain',
    'https://www.google.com/maps/search/?api=1&query=Seunghaksan+Mountain+Busan',
    'https://map.naver.com/p/search/Seunghaksan%20Mountain%20Busan',
    35.1155, 128.9817, 180, 'afternoon', NULL,
    ARRAY['#Hiking','#ReedField','#RiverView','#Sunset'],
    true, true, false, 'manual', 'Free', 'moderate',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Dongbaekseom Island Walking Trail', 'Nature', 'Haeundae-gu',
    'Dongbaek-ro, Haeundae-gu, Busan',
    'A short seaside walking loop beside Haeundae with Nurimaru and bridge views',
    'Easy premium walk for hotel guests and first time visitors',
    'https://source.unsplash.com/1200x800/?busan,coastal,walk',
    'https://www.google.com/maps/search/?api=1&query=Dongbaekseom+Island+Busan',
    'https://map.naver.com/p/search/Dongbaekseom%20Island%20Busan',
    35.1517, 129.1527, 60, 'morning', NULL,
    ARRAY['#Walking','#OceanView','#Haeundae','#Easy'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1',
    'booking'
  ),
  (
    'busan', 'Nurimaru APEC House', 'Landmark', 'Haeundae-gu',
    '116 Dongbaek-ro, Haeundae-gu, Busan',
    'A seaside conference landmark on Dongbaekseom with coastal views',
    'Adds international landmark credibility to Haeundae walking routes',
    'https://source.unsplash.com/1200x800/?busan,apec',
    'https://www.google.com/maps/search/?api=1&query=Nurimaru+APEC+House+Busan',
    'https://map.naver.com/p/search/Nurimaru%20APEC%20House%20Busan',
    35.1527, 129.1522, 45, 'afternoon',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#Landmark','#OceanView','#APEC','#Haeundae'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1',
    'booking'
  ),
  (
    'busan', 'Cheongsapo Daritdol Observatory', 'Viewpoint', 'Haeundae-gu',
    'Cheongsapo-ro, Haeundae-gu, Busan',
    'A coastal skywalk observatory near Cheongsapo and Blue Line Park',
    'Strong photo stop connected to rail bike and cafe spending',
    'https://source.unsplash.com/1200x800/?busan,skywalk,sea',
    'https://www.google.com/maps/search/?api=1&query=Cheongsapo+Daritdol+Observatory+Busan',
    'https://map.naver.com/p/search/Cheongsapo%20Daritdol%20Observatory%20Busan',
    35.1601, 129.1918, 45, 'afternoon',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#Skywalk','#OceanView','#BlueLine','#PhotoSpot'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Haeundae Blue Line Park', 'Attraction', 'Haeundae-gu',
    '13 Dalmaji-gil 62beon-gil, Haeundae-gu, Busan',
    'A coastal railway attraction with beach train and sky capsule routes',
    'One of Busan''s best paid attraction products for affiliate conversion',
    'https://source.unsplash.com/1200x800/?busan,train,sea',
    'https://www.google.com/maps/search/?api=1&query=Haeundae+Blue+Line+Park+Busan',
    'https://map.naver.com/p/search/Haeundae%20Blue%20Line%20Park%20Busan',
    35.1588, 129.1810, 120, 'afternoon',
    '{"open":"09:30","close":"19:00"}'::jsonb,
    ARRAY['#PaidAttraction','#OceanView','#SkyCapsule','#Haeundae'],
    true, true, false, 'manual', '₩7,000', NULL,
    'https://www.bluelinepark.com',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Dalmaji Hill', 'Cafe Street', 'Haeundae-gu',
    'Dalmaji-gil, Haeundae-gu, Busan',
    'A scenic hill road with cafes cherry blossoms and ocean views',
    'Excellent romantic cafe and accommodation upsell connector near Haeundae',
    'https://source.unsplash.com/1200x800/?busan,cafe,sea',
    'https://www.google.com/maps/search/?api=1&query=Dalmaji+Hill+Busan',
    'https://map.naver.com/p/search/Dalmaji%20Hill%20Busan',
    35.1580, 129.1823, 90, 'afternoon', NULL,
    ARRAY['#Cafe','#OceanView','#CherryBlossom','#Haeundae'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1',
    'booking'
  ),
  (
    'busan', 'The Bay 101', 'Landmark', 'Haeundae-gu',
    '52 Dongbaek-ro, Haeundae-gu, Busan',
    'A marina side night view and dining complex near Haeundae',
    'High commercial value for nightlife hotel and food spending routes',
    'https://source.unsplash.com/1200x800/?busan,marina,night',
    'https://www.google.com/maps/search/?api=1&query=The+Bay+101+Busan',
    'https://map.naver.com/p/search/The%20Bay%20101%20Busan',
    35.1564, 129.1517, 60, 'night',
    '{"open":"09:00","close":"24:00"}'::jsonb,
    ARRAY['#NightView','#Marina','#Dining','#Haeundae'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.thebay101.com',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1',
    'booking'
  ),
  (
    'busan', 'Busan X the Sky', 'Observatory', 'Haeundae-gu',
    '30 Dalmaji-gil, Haeundae-gu, Busan',
    'A high rise observatory inside LCT with wide views of Haeundae and the sea',
    'Premium paid attraction with strong affiliate and ticket conversion value',
    'https://source.unsplash.com/1200x800/?busan,observatory',
    'https://www.google.com/maps/search/?api=1&query=Busan+X+the+Sky',
    'https://map.naver.com/p/search/Busan%20X%20the%20Sky',
    35.1595, 129.1690, 90, 'sunset',
    '{"open":"10:00","close":"21:00"}'::jsonb,
    ARRAY['#Observatory','#PaidAttraction','#Haeundae','#Luxury'],
    true, true, false, 'manual', '₩27,000', NULL,
    'https://www.busanxthesky.com',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'Songdo Marine Cable Car', 'Attraction', 'Seo-gu',
    '171 Songdohaebyeon-ro, Seo-gu, Busan',
    'A cable car crossing the sea between Songdo Beach and Amnam Park',
    'Direct paid product and strong family travel conversion point',
    'https://source.unsplash.com/1200x800/?busan,cablecar,sea',
    'https://www.google.com/maps/search/?api=1&query=Songdo+Marine+Cable+Car+Busan',
    'https://map.naver.com/p/search/Songdo%20Marine%20Cable%20Car%20Busan',
    35.0778, 129.0207, 90, 'afternoon',
    '{"open":"09:00","close":"20:00"}'::jsonb,
    ARRAY['#CableCar','#PaidAttraction','#OceanView','#Family'],
    true, true, false, 'manual', '₩17,000', NULL,
    'https://en.busanaircruise.co.kr',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  ),
  (
    'busan', 'National Maritime Museum', 'Museum', 'Yeongdo-gu',
    '45 Haeyang-ro 301beon-gil, Yeongdo-gu, Busan',
    'A large maritime museum covering ocean culture ships and marine history',
    'Strong family and rainy day stop near Yeongdo coastal routes',
    'https://source.unsplash.com/1200x800/?maritime,museum',
    'https://www.google.com/maps/search/?api=1&query=National+Maritime+Museum+Busan',
    'https://map.naver.com/p/search/National%20Maritime%20Museum%20Busan',
    35.0789, 129.0803, 120, 'afternoon',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#Museum','#Maritime','#Family','#Indoor'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.mmk.or.kr',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/',
    'klook'
  )
ON CONFLICT (city, name) DO NOTHING;

-- 3) 검증 쿼리
SELECT city, COUNT(*) FROM city_spots GROUP BY city ORDER BY city;
SELECT source_type, COUNT(*) FROM city_spots GROUP BY source_type ORDER BY source_type;
SELECT affiliate_provider, COUNT(*) FROM city_spots GROUP BY affiliate_provider ORDER BY affiliate_provider;

COMMIT;
