-- [운영 적용 이력] 2026-07-03 / Supabase Studio SQL Editor 수동 실행 (014 migration 이전)
-- [소스 관리 편입 목적] 데이터 이력 보존 — "미실행 파일" 오인 방지
-- [재실행 안전성] ON CONFLICT (city, name) DO NOTHING → 기존 row 보호.
--               이 파일은 신규 데이터 추가용 템플릿이 아님.
--               014 category normalization 이후 신규 city_spots insert는
--               반드시 표준 category 만 사용할 것:
--               'attraction' / 'restaurant' / 'nature' / 'event' / 'accommodation'
--               이 파일의 비표준 category 값('Beach','Mountain Trail' 등)을 포함한
--               신규 row는 CHECK constraint(city_spots_category_check) 위반으로 실패함.

BEGIN;

INSERT INTO city_spots
  (city, name, category, district, address, description, why_it_matters,
   image_url, map_url, naver_map_url, lat, lng,
   duration_minutes, best_time_slot, opening_hours, tags,
   solo_friendly, foreign_card_accepted, cash_only, source_type,
   entry_fee, difficulty, official_url, affiliate_url, affiliate_provider)
VALUES
  (
    'busan', 'Amnam Park Coastal Trail', 'Nature', 'Seo-gu',
    'Amnam-dong, Seo-gu, Busan',
    'A forested coastal park connected to Songdo cable car and sea cliffs',
    'Good hiking add on after paid cable car attraction',
    'https://source.unsplash.com/1200x800/?busan,forest,coast',
    'https://www.google.com/maps/search/?api=1&query=Amnam+Park+Busan',
    'https://map.naver.com/p/search/Amnam%20Park%20Busan',
    35.0652, 129.0190, 120, 'morning', NULL,
    ARRAY['#CoastalWalk','#Forest','#CableCar','#Free'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Huinnyeoul Culture Village', 'Culture', 'Yeongdo-gu',
    'Huinnyeoul-gil, Yeongdo-gu, Busan',
    'A seaside village walkway with murals cafes and ocean views',
    'High photo and cafe spending value near Yeongdo coastal routes',
    'https://source.unsplash.com/1200x800/?busan,village,sea',
    'https://www.google.com/maps/search/?api=1&query=Huinnyeoul+Culture+Village+Busan',
    'https://map.naver.com/p/search/Huinnyeoul%20Culture%20Village%20Busan',
    35.0788, 129.0446, 90, 'afternoon', NULL,
    ARRAY['#CultureVillage','#OceanView','#Cafe','#PhotoSpot'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Jeoryeong Coastal Walk', 'Walking Trail', 'Yeongdo-gu',
    'Jeoryeong-ro, Yeongdo-gu, Busan',
    'A coastal walking path below Huinnyeoul with sea and cliff views',
    'Excellent free walking content for Yeongdo day itineraries',
    'https://source.unsplash.com/1200x800/?busan,coastal,path',
    'https://www.google.com/maps/search/?api=1&query=Jeoryeong+Coastal+Walk+Busan',
    'https://map.naver.com/p/search/Jeoryeong%20Coastal%20Walk%20Busan',
    35.0770, 129.0467, 90, 'morning', NULL,
    ARRAY['#Walking','#OceanView','#Yeongdo','#Free'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Yeongdo Taejongdae Lighthouse', 'Landmark', 'Yeongdo-gu',
    'Taejongdae, Yeongdo-gu, Busan',
    'A coastal lighthouse area reached through Taejongdae forest and cliff paths',
    'Adds iconic endpoint value to Taejongdae nature routes',
    'https://source.unsplash.com/1200x800/?busan,lighthouse',
    'https://www.google.com/maps/search/?api=1&query=Taejongdae+Lighthouse+Busan',
    'https://map.naver.com/p/search/Taejongdae%20Lighthouse%20Busan',
    35.0507, 129.0873, 120, 'afternoon', NULL,
    ARRAY['#Lighthouse','#CoastalWalk','#Cliff','#OceanView'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Busan Harbor Bridge Viewpoint', 'Viewpoint', 'Yeongdo-gu',
    'Cheonghak-dong, Yeongdo-gu, Busan',
    'A viewpoint area overlooking Busan Harbor Bridge and port night lights',
    'Useful night photography stop for Yeongdo taxi routes',
    'https://source.unsplash.com/1200x800/?busan,harbor,bridge',
    'https://www.google.com/maps/search/?api=1&query=Busan+Harbor+Bridge+Viewpoint',
    'https://map.naver.com/p/search/Busan%20Harbor%20Bridge%20Viewpoint',
    35.0912, 129.0647, 45, 'night', NULL,
    ARRAY['#NightView','#BridgeView','#Harbor','#PhotoSpot'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'UN Memorial Cemetery in Korea', 'History', 'Nam-gu',
    '93 UN Pyeonghwa-ro, Nam-gu, Busan',
    'A solemn memorial cemetery honoring UN soldiers from the Korean War',
    'Important history stop for international visitors and educational tours',
    'https://source.unsplash.com/1200x800/?korea,memorial',
    'https://www.google.com/maps/search/?api=1&query=UN+Memorial+Cemetery+Busan',
    'https://map.naver.com/p/search/UN%20Memorial%20Cemetery%20Busan',
    35.1276, 129.0969, 90, 'morning',
    '{"open":"09:00","close":"17:00"}'::jsonb,
    ARRAY['#History','#Memorial','#UN','#Education'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.unmck.or.kr',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Busan Museum', 'History', 'Nam-gu',
    '63 UN Pyeonghwa-ro, Nam-gu, Busan',
    'A city history museum near the UN Memorial Cemetery',
    'Good rainy day and educational itinerary anchor',
    'https://source.unsplash.com/1200x800/?korea,museum',
    'https://www.google.com/maps/search/?api=1&query=Busan+Museum',
    'https://map.naver.com/p/search/Busan%20Museum',
    35.1292, 129.0915, 90, 'afternoon',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#Museum','#History','#Indoor','#RainyDay'],
    true, true, false, 'manual', 'Free', NULL,
    'https://museum.busan.go.kr',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Busan Citizens Park', 'Park', 'Busanjin-gu',
    '73 Simingongwon-ro, Busanjin-gu, Busan',
    'A large urban park built on a former military base near Seomyeon',
    'Strong local lifestyle stop for families and slow travel users',
    'https://source.unsplash.com/1200x800/?busan,park',
    'https://www.google.com/maps/search/?api=1&query=Busan+Citizens+Park',
    'https://map.naver.com/p/search/Busan%20Citizens%20Park',
    35.1687, 129.0556, 90, 'afternoon',
    '{"open":"05:00","close":"24:00"}'::jsonb,
    ARRAY['#Park','#UrbanWalk','#Family','#Seomyeon'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Jeonpo Cafe Street', 'Cafe Street', 'Busanjin-gu',
    'Jeonpo-dong, Busanjin-gu, Busan',
    'A trendy cafe and small shop district near Seomyeon',
    'High spending potential for cafes shopping and boutique hotels',
    'https://source.unsplash.com/1200x800/?korea,cafe,street',
    'https://www.google.com/maps/search/?api=1&query=Jeonpo+Cafe+Street+Busan',
    'https://map.naver.com/p/search/Jeonpo%20Cafe%20Street%20Busan',
    35.1579, 129.0632, 90, 'afternoon',
    '{"open":"10:00","close":"22:00"}'::jsonb,
    ARRAY['#Cafe','#Shopping','#Trendy','#Seomyeon'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Seomyeon Shopping District', 'Shopping', 'Busanjin-gu',
    'Seomyeon-ro, Busanjin-gu, Busan',
    'Busan''s central shopping nightlife and transit district',
    'Best commercial base for hotel nightlife and restaurant affiliate funnels',
    'https://source.unsplash.com/1200x800/?korea,shopping,night',
    'https://www.google.com/maps/search/?api=1&query=Seomyeon+Busan',
    'https://map.naver.com/p/search/Seomyeon%20Busan',
    35.1577, 129.0590, 120, 'evening', NULL,
    ARRAY['#Shopping','#Nightlife','#Food','#Transit'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Samgwangsa Temple', 'Temple', 'Busanjin-gu',
    '77 Choeupcheon-ro 43beon-gil, Busanjin-gu, Busan',
    'A large temple famous for lantern displays and hillside views',
    'Strong seasonal content during lantern festival periods',
    'https://source.unsplash.com/1200x800/?korea,lantern,temple',
    'https://www.google.com/maps/search/?api=1&query=Samgwangsa+Temple+Busan',
    'https://map.naver.com/p/search/Samgwangsa%20Temple%20Busan',
    35.1750, 129.0503, 90, 'evening',
    '{"open":"05:00","close":"22:00"}'::jsonb,
    ARRAY['#Temple','#Lanterns','#Festival','#PhotoSpot'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Oncheoncheon Stream Park', 'Walking Trail', 'Dongnae-gu',
    'Oncheoncheon-ro, Dongnae-gu, Busan',
    'A long urban stream walk with cafes cherry blossoms and cycling paths',
    'Good local slow travel and cafe affiliate route in north Busan',
    'https://source.unsplash.com/1200x800/?korea,stream,walk',
    'https://www.google.com/maps/search/?api=1&query=Oncheoncheon+Stream+Busan',
    'https://map.naver.com/p/search/Oncheoncheon%20Stream%20Busan',
    35.2007, 129.0830, 90, 'afternoon', NULL,
    ARRAY['#Walking','#CherryBlossom','#Cafe','#Local'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Dongnae Eupseong Fortress', 'History', 'Dongnae-gu',
    'Myeongnyun-dong, Dongnae-gu, Busan',
    'Historic fortress remains in old Dongnae with cultural walking routes',
    'Useful for heritage content outside the standard beach itinerary',
    'https://source.unsplash.com/1200x800/?korea,fortress,history',
    'https://www.google.com/maps/search/?api=1&query=Dongnae+Eupseong+Fortress+Busan',
    'https://map.naver.com/p/search/Dongnae%20Eupseong%20Fortress%20Busan',
    35.2057, 129.0838, 90, 'morning', NULL,
    ARRAY['#History','#Fortress','#Walking','#Local'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Geumgang Park', 'Park', 'Dongnae-gu',
    '155 Ujangchun-ro, Dongnae-gu, Busan',
    'A forest park below Geumjeongsan with trails and cable car access nearby',
    'Gateway to north Busan hiking and family nature content',
    'https://source.unsplash.com/1200x800/?korea,forest,park',
    'https://www.google.com/maps/search/?api=1&query=Geumgang+Park+Busan',
    'https://map.naver.com/p/search/Geumgang%20Park%20Busan',
    35.2212, 129.0795, 120, 'morning', NULL,
    ARRAY['#Park','#Forest','#Hiking','#Family'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Seokbulsa Temple', 'Temple', 'Buk-gu',
    '143-79 Mandeokgogae-gil, Buk-gu, Busan',
    'A cliffside temple known for carved stone Buddha reliefs',
    'Hidden gem hiking content with strong discovery value for foreigners',
    'https://source.unsplash.com/1200x800/?korea,stone,temple',
    'https://www.google.com/maps/search/?api=1&query=Seokbulsa+Temple+Busan',
    'https://map.naver.com/p/search/Seokbulsa%20Temple%20Busan',
    35.2241, 129.0494, 150, 'morning',
    '{"open":"08:00","close":"18:00"}'::jsonb,
    ARRAY['#Temple','#HiddenGem','#Hiking','#StoneCarving'],
    true, true, false, 'manual', 'Free', 'moderate',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Mandeok Pass Deck', 'Viewpoint', 'Buk-gu',
    'Mandeokgogae-gil, Buk-gu, Busan',
    'A mountain pass viewpoint between Mandeok and Geumjeongsan routes',
    'Useful local viewpoint for hiking route extension around Seokbulsa',
    'https://source.unsplash.com/1200x800/?busan,mountain,view',
    'https://www.google.com/maps/search/?api=1&query=Mandeok+Pass+Busan',
    'https://map.naver.com/p/search/Mandeok%20Pass%20Busan',
    35.2207, 129.0438, 45, 'sunset', NULL,
    ARRAY['#Viewpoint','#Mountain','#Local','#Free'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Hwamyeong Ecological Park', 'Park', 'Buk-gu',
    'Hwamyeong-dong, Buk-gu, Busan',
    'A riverside ecological park along the Nakdong River',
    'Good picnic cycling and family route for west Busan expansion',
    'https://source.unsplash.com/1200x800/?korea,river,park',
    'https://www.google.com/maps/search/?api=1&query=Hwamyeong+Ecological+Park+Busan',
    'https://map.naver.com/p/search/Hwamyeong%20Ecological%20Park%20Busan',
    35.2344, 129.0038, 120, 'afternoon', NULL,
    ARRAY['#RiverPark','#Cycling','#Family','#Sunset'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Hwamyeong Arboretum', 'Nature', 'Buk-gu',
    '299-11 Sanseong-ro, Buk-gu, Busan',
    'A forest arboretum with seasonal plants and gentle walking paths',
    'Useful nature stop for family and slow travel itineraries',
    'https://source.unsplash.com/1200x800/?korea,arboretum,forest',
    'https://www.google.com/maps/search/?api=1&query=Hwamyeong+Arboretum+Busan',
    'https://map.naver.com/p/search/Hwamyeong%20Arboretum%20Busan',
    35.2452, 129.0449, 90, 'morning',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#Arboretum','#Forest','#Family','#Free'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Nakdong River Estuary Eco Center', 'Nature', 'Saha-gu',
    '1240 Nakdongnam-ro, Saha-gu, Busan',
    'An ecological center near migratory bird habitats and river wetlands',
    'Good educational nature content for eco travel positioning',
    'https://source.unsplash.com/1200x800/?korea,wetland,birds',
    'https://www.google.com/maps/search/?api=1&query=Nakdong+River+Estuary+Eco+Center+Busan',
    'https://map.naver.com/p/search/Nakdong%20River%20Estuary%20Eco%20Center%20Busan',
    35.1049, 128.9467, 90, 'morning',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#EcoTravel','#Wetland','#Birdwatching','#Family'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.busan.go.kr/wetland',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Eulsukdo Island', 'Park', 'Saha-gu',
    'Eulsukdo, Saha-gu, Busan',
    'A river island park known for wetlands migratory birds and cultural spaces',
    'Differentiates Busan beyond beaches with eco and family travel appeal',
    'https://source.unsplash.com/1200x800/?korea,river,island',
    'https://www.google.com/maps/search/?api=1&query=Eulsukdo+Island+Busan',
    'https://map.naver.com/p/search/Eulsukdo%20Island%20Busan',
    35.1096, 128.9463, 120, 'afternoon', NULL,
    ARRAY['#IslandPark','#Wetland','#Birdwatching','#Eco'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Busan Museum of Contemporary Art', 'Art', 'Saha-gu',
    '1191 Nakdongnam-ro, Saha-gu, Busan',
    'A contemporary art museum on Eulsukdo Island',
    'Good indoor art stop paired with eco park and west Busan routes',
    'https://source.unsplash.com/1200x800/?contemporary,art,museum',
    'https://www.google.com/maps/search/?api=1&query=Busan+Museum+of+Contemporary+Art',
    'https://map.naver.com/p/search/Busan%20Museum%20of%20Contemporary%20Art',
    35.1099, 128.9427, 90, 'afternoon',
    '{"open":"10:00","close":"18:00"}'::jsonb,
    ARRAY['#Museum','#Art','#Indoor','#Eulsukdo'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.busan.go.kr/moca',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Ahopsan Forest', 'Nature', 'Gijang-gun',
    '37-1 Midong-gil, Cheolma-myeon, Gijang-gun, Busan',
    'A private bamboo and forest walking destination in Gijang',
    'High quality nature photo spot with tour package potential',
    'https://source.unsplash.com/1200x800/?bamboo,forest,korea',
    'https://www.google.com/maps/search/?api=1&query=Ahopsan+Forest+Busan',
    'https://map.naver.com/p/search/Ahopsan%20Forest%20Busan',
    35.2894, 129.1464, 90, 'morning',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#Forest','#Bamboo','#PhotoSpot','#Gijang'],
    true, true, false, 'manual', '₩8,000', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Ananti Cove Gijang', 'Resort Area', 'Gijang-gun',
    '268-32 Gijanghaean-ro, Gijang-gun, Busan',
    'A luxury seaside resort and cafe zone on the Gijang coast',
    'Premium accommodation affiliate anchor for high value travelers',
    'https://source.unsplash.com/1200x800/?luxury,resort,sea',
    'https://www.google.com/maps/search/?api=1&query=Ananti+Cove+Busan',
    'https://map.naver.com/p/search/Ananti%20Cove%20Busan',
    35.1979, 129.2276, 90, 'afternoon', NULL,
    ARRAY['#Luxury','#Resort','#Cafe','#OceanView'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.ananti.kr',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Busan Lotte World Adventure', 'Theme Park', 'Gijang-gun',
    '42 Dongbusangwangwang-ro, Gijang-gun, Busan',
    'A major theme park in the Osiria tourism complex',
    'Strong family ticket and hotel package affiliate opportunity',
    'https://source.unsplash.com/1200x800/?theme,park,korea',
    'https://www.google.com/maps/search/?api=1&query=Lotte+World+Adventure+Busan',
    'https://map.naver.com/p/search/Lotte%20World%20Adventure%20Busan',
    35.1922, 129.2138, 240, 'morning',
    '{"open":"10:00","close":"21:00"}'::jsonb,
    ARRAY['#ThemePark','#Family','#PaidAttraction','#Gijang'],
    true, true, false, 'manual', '₩47,000', NULL,
    'https://adventurebusan.lotteworld.com',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Osiria Coastal Walk', 'Walking Trail', 'Gijang-gun',
    'Gijanghaean-ro, Gijang-gun, Busan',
    'A coastal tourism zone linking resorts cafes and sea views',
    'Strategic route for accommodation shopping and family travel monetization',
    'https://source.unsplash.com/1200x800/?busan,gijang,coast',
    'https://www.google.com/maps/search/?api=1&query=Osiria+Busan',
    'https://map.naver.com/p/search/Osiria%20Busan',
    35.1938, 129.2148, 120, 'afternoon', NULL,
    ARRAY['#CoastalWalk','#Resort','#Family','#Gijang'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Busan National Science Museum', 'Museum', 'Gijang-gun',
    '59 Dongbusangwangwang 6-ro, Gijang-gun, Busan',
    'A large science museum in the Osiria area for families and children',
    'Good family itinerary asset near theme park and resorts',
    'https://source.unsplash.com/1200x800/?science,museum,korea',
    'https://www.google.com/maps/search/?api=1&query=Busan+National+Science+Museum',
    'https://map.naver.com/p/search/Busan%20National%20Science%20Museum',
    35.2040, 129.2127, 120, 'afternoon',
    '{"open":"09:30","close":"17:30"}'::jsonb,
    ARRAY['#Museum','#Family','#Indoor','#Education'],
    true, true, false, 'manual', '₩3,000', NULL,
    'https://www.sciport.or.kr',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Ilgwang Beach', 'Beach', 'Gijang-gun',
    'Ilgwang-myeon, Gijang-gun, Busan',
    'A quieter beach in Gijang with local seafood and coastal scenery',
    'Good hidden beach content for repeat travelers and car routes',
    'https://source.unsplash.com/1200x800/?korea,beach,quiet',
    'https://www.google.com/maps/search/?api=1&query=Ilgwang+Beach+Busan',
    'https://map.naver.com/p/search/Ilgwang%20Beach%20Busan',
    35.2613, 129.2330, 90, 'afternoon', NULL,
    ARRAY['#Beach','#Local','#Seafood','#Gijang'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Jukseong Dream Church', 'Landmark', 'Gijang-gun',
    'Jukseong-ri, Gijang-gun, Busan',
    'A picturesque seaside filming location shaped like a small church',
    'Photo stop with strong social media appeal on Gijang coastal drives',
    'https://source.unsplash.com/1200x800/?korea,church,sea',
    'https://www.google.com/maps/search/?api=1&query=Jukseong+Dream+Church+Busan',
    'https://map.naver.com/p/search/Jukseong%20Dream%20Church%20Busan',
    35.2370, 129.2454, 45, 'afternoon', NULL,
    ARRAY['#PhotoSpot','#OceanView','#Gijang','#FilmingLocation'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Busan Cinema Center', 'Landmark', 'Haeundae-gu',
    '120 Suyeonggangbyeon-daero, Haeundae-gu, Busan',
    'The symbolic venue of the Busan International Film Festival',
    'Important modern landmark for culture tourism and night photography',
    'https://source.unsplash.com/1200x800/?busan,cinema,center',
    'https://www.google.com/maps/search/?api=1&query=Busan+Cinema+Center',
    'https://map.naver.com/p/search/Busan%20Cinema%20Center',
    35.1710, 129.1270, 60, 'night',
    '{"open":"09:00","close":"22:00"}'::jsonb,
    ARRAY['#Cinema','#Architecture','#NightView','#Centum'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.dureraum.org',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Shinsegae Centum City', 'Shopping', 'Haeundae-gu',
    '35 Centumnam-daero, Haeundae-gu, Busan',
    'A huge shopping complex in Centum City with department store spa and dining',
    'Major commercial stop for shopping food and indoor rainy day monetization',
    'https://source.unsplash.com/1200x800/?shopping,mall,korea',
    'https://www.google.com/maps/search/?api=1&query=Shinsegae+Centum+City+Busan',
    'https://map.naver.com/p/search/Shinsegae%20Centum%20City%20Busan',
    35.1698, 129.1290, 150, 'afternoon',
    '{"open":"10:30","close":"20:30"}'::jsonb,
    ARRAY['#Shopping','#Indoor','#Luxury','#Centum'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.shinsegae.com',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Millak Waterfront Park', 'Park', 'Suyeong-gu',
    'Millak-dong, Suyeong-gu, Busan',
    'A waterfront park with views of Gwangalli and Gwangan Bridge',
    'Strong casual night picnic stop near seafood and beach hotels',
    'https://source.unsplash.com/1200x800/?busan,waterfront,night',
    'https://www.google.com/maps/search/?api=1&query=Millak+Waterfront+Park+Busan',
    'https://map.naver.com/p/search/Millak%20Waterfront%20Park%20Busan',
    35.1547, 129.1328, 60, 'evening', NULL,
    ARRAY['#Waterfront','#NightView','#BridgeView','#Local'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'F1963', 'Culture', 'Suyeong-gu',
    '20 Gurak-ro 123beon-gil, Suyeong-gu, Busan',
    'A regenerated cultural complex with books cafes exhibitions and gardens',
    'Good indoor cultural stop for premium lifestyle travelers',
    'https://source.unsplash.com/1200x800/?korea,culture,complex',
    'https://www.google.com/maps/search/?api=1&query=F1963+Busan',
    'https://map.naver.com/p/search/F1963%20Busan',
    35.1760, 129.1133, 90, 'afternoon',
    '{"open":"10:00","close":"21:00"}'::jsonb,
    ARRAY['#Culture','#Cafe','#Books','#Indoor'],
    true, true, false, 'manual', 'Free', NULL,
    'https://f1963.org',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Busan Modern History Museum', 'History', 'Jung-gu',
    '104 Daecheong-ro, Jung-gu, Busan',
    'A museum explaining Busan''s modern history in the old downtown',
    'Good context stop near Nampo markets and Yongdusan Park',
    'https://source.unsplash.com/1200x800/?history,museum,korea',
    'https://www.google.com/maps/search/?api=1&query=Busan+Modern+History+Museum',
    'https://map.naver.com/p/search/Busan%20Modern%20History%20Museum',
    35.1023, 129.0315, 60, 'afternoon',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#Museum','#History','#Nampo','#Indoor'],
    true, true, false, 'manual', 'Free', NULL,
    'https://museum.busan.go.kr',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Bosu-dong Book Street', 'Culture', 'Jung-gu',
    'Bosu-dong, Jung-gu, Busan',
    'A historic alley of secondhand bookstores near Gukje Market',
    'Niche cultural stop for slow travel and rainy day content',
    'https://source.unsplash.com/1200x800/?book,street,korea',
    'https://www.google.com/maps/search/?api=1&query=Bosu-dong+Book+Street+Busan',
    'https://map.naver.com/p/search/Bosu-dong%20Book%20Street%20Busan',
    35.1029, 129.0266, 60, 'afternoon',
    '{"open":"10:00","close":"19:00"}'::jsonb,
    ARRAY['#Books','#Culture','#Nampo','#HiddenGem'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', '40-step Culture and Tourism Theme Street', 'Culture', 'Jung-gu',
    'Jungang-dong, Jung-gu, Busan',
    'A historic themed street remembering postwar Busan life',
    'Useful old downtown walking connector from Busan Station to Nampo',
    'https://source.unsplash.com/1200x800/?korea,street,history',
    'https://www.google.com/maps/search/?api=1&query=40-step+Culture+Street+Busan',
    'https://map.naver.com/p/search/40-step%20Culture%20Street%20Busan',
    35.1053, 129.0351, 45, 'afternoon', NULL,
    ARRAY['#History','#Walking','#OldTown','#PhotoSpot'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Busan Station', 'Transit Landmark', 'Dong-gu',
    '206 Jungang-daero, Dong-gu, Busan',
    'The main rail gateway to Busan and a practical itinerary starting point',
    'Important arrival anchor for itinerary generation and hotel conversion',
    'https://source.unsplash.com/1200x800/?busan,station',
    'https://www.google.com/maps/search/?api=1&query=Busan+Station',
    'https://map.naver.com/p/search/Busan%20Station',
    35.1151, 129.0415, 30, 'arrival', NULL,
    ARRAY['#Transit','#KTX','#Arrival','#HotelArea'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.letskorail.com',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', '168 Stairs and Monorail Area', 'Walking Trail', 'Dong-gu',
    'Yeongcho-gil, Dong-gu, Busan',
    'A hillside stair and viewpoint area near Busan Station',
    'Great short urban hike for travelers staying near the station',
    'https://source.unsplash.com/1200x800/?korea,stairs,village',
    'https://www.google.com/maps/search/?api=1&query=168+Stairs+Busan',
    'https://map.naver.com/p/search/168%20Stairs%20Busan',
    35.1172, 129.0353, 60, 'morning', NULL,
    ARRAY['#UrbanHike','#Viewpoint','#BusanStation','#Free'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Choryang Ibagu-gil', 'Walking Trail', 'Dong-gu',
    'Choryang-dong, Dong-gu, Busan',
    'A hillside story road with old alleys viewpoints and local history',
    'Strong low cost walking content right after KTX arrival',
    'https://source.unsplash.com/1200x800/?busan,alley,view',
    'https://www.google.com/maps/search/?api=1&query=Choryang+Ibagu-gil+Busan',
    'https://map.naver.com/p/search/Choryang%20Ibagu-gil%20Busan',
    35.1184, 129.0365, 90, 'morning', NULL,
    ARRAY['#Walking','#History','#Viewpoint','#Local'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Provisional Capital Memorial Hall', 'History', 'Seo-gu',
    '45 Imsisudoginyeom-ro, Seo-gu, Busan',
    'A historic site related to Busan''s role during the Korean War',
    'Meaningful educational stop near old downtown and university hospital area',
    'https://source.unsplash.com/1200x800/?korea,heritage,house',
    'https://www.google.com/maps/search/?api=1&query=Provisional+Capital+Memorial+Hall+Busan',
    'https://map.naver.com/p/search/Provisional%20Capital%20Memorial%20Hall%20Busan',
    35.1038, 129.0195, 60, 'afternoon',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#History','#KoreanWar','#Museum','#Education'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Songdo Yonggung Suspension Bridge', 'Attraction', 'Seo-gu',
    'Amnam Park, Seo-gu, Busan',
    'A suspension bridge over coastal cliffs near Songdo and Amnam Park',
    'Paid coastal photo attraction that pairs with cable car tickets',
    'https://source.unsplash.com/1200x800/?suspension,bridge,sea',
    'https://www.google.com/maps/search/?api=1&query=Songdo+Yonggung+Suspension+Bridge+Busan',
    'https://map.naver.com/p/search/Songdo%20Yonggung%20Suspension%20Bridge%20Busan',
    35.0616, 129.0174, 60, 'afternoon',
    '{"open":"09:00","close":"18:00"}'::jsonb,
    ARRAY['#SuspensionBridge','#OceanView','#PaidAttraction','#Songdo'],
    true, true, false, 'manual', '₩1,000', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Samnak Ecological Park', 'Park', 'Sasang-gu',
    'Samnak-dong, Sasang-gu, Busan',
    'A vast riverside ecological park along the Nakdong River',
    'Good cycling picnic and seasonal flower content for west Busan',
    'https://source.unsplash.com/1200x800/?korea,river,flowers',
    'https://www.google.com/maps/search/?api=1&query=Samnak+Ecological+Park+Busan',
    'https://map.naver.com/p/search/Samnak%20Ecological%20Park%20Busan',
    35.1688, 128.9752, 120, 'afternoon', NULL,
    ARRAY['#RiverPark','#Cycling','#Picnic','#Flowers'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Maekdo Ecological Park', 'Park', 'Gangseo-gu',
    'Daejeo 2-dong, Gangseo-gu, Busan',
    'A wide riverside eco park near Gimhae Airport and Nakdong River',
    'Useful airport side nature stop for arrival or departure day',
    'https://source.unsplash.com/1200x800/?wetland,park,korea',
    'https://www.google.com/maps/search/?api=1&query=Maekdo+Ecological+Park+Busan',
    'https://map.naver.com/p/search/Maekdo%20Ecological%20Park%20Busan',
    35.1696, 128.9540, 90, 'afternoon', NULL,
    ARRAY['#EcoPark','#AirportNearby','#River','#Free'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Daejeo Ecological Park', 'Park', 'Gangseo-gu',
    'Daejeo 1-dong, Gangseo-gu, Busan',
    'A riverside park known for seasonal flowers and wide open fields',
    'Strong seasonal content for spring flowers and local photography',
    'https://source.unsplash.com/1200x800/?korea,flower,field',
    'https://www.google.com/maps/search/?api=1&query=Daejeo+Ecological+Park+Busan',
    'https://map.naver.com/p/search/Daejeo%20Ecological%20Park%20Busan',
    35.2140, 128.9713, 120, 'afternoon', NULL,
    ARRAY['#FlowerField','#RiverPark','#PhotoSpot','#Seasonal'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Gadeokdo Island', 'Island', 'Gangseo-gu',
    'Gadeokdo, Gangseo-gu, Busan',
    'A large island at Busan''s western edge with coastal villages and sea views',
    'Future growth area for offbeat coastal routes and local seafood travel',
    'https://source.unsplash.com/1200x800/?korea,island,sea',
    'https://www.google.com/maps/search/?api=1&query=Gadeokdo+Island+Busan',
    'https://map.naver.com/p/search/Gadeokdo%20Island%20Busan',
    35.0133, 128.8307, 180, 'afternoon', NULL,
    ARRAY['#Island','#Seafood','#CoastalDrive','#HiddenGem'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Sinseondae Terrace', 'Viewpoint', 'Nam-gu',
    'Sinseondae, Nam-gu, Busan',
    'A coastal and harbor viewpoint with dramatic port scenery',
    'Good photography spot for travelers interested in Busan''s port identity',
    'https://source.unsplash.com/1200x800/?busan,port,view',
    'https://www.google.com/maps/search/?api=1&query=Sinseondae+Busan',
    'https://map.naver.com/p/search/Sinseondae%20Busan',
    35.1048, 129.1048, 60, 'afternoon', NULL,
    ARRAY['#Viewpoint','#Harbor','#Coast','#PhotoSpot'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Busan Air Cruise Songdo Sky Park', 'Attraction', 'Seo-gu',
    '181 Amnamgongwon-ro, Seo-gu, Busan',
    'The upper cable car park area with ocean views and photo zones',
    'Completes the Songdo paid attraction funnel after cable car purchase',
    'https://source.unsplash.com/1200x800/?busan,skypark,sea',
    'https://www.google.com/maps/search/?api=1&query=Songdo+Sky+Park+Busan',
    'https://map.naver.com/p/search/Songdo%20Sky%20Park%20Busan',
    35.0648, 129.0181, 60, 'afternoon',
    '{"open":"09:00","close":"20:00"}'::jsonb,
    ARRAY['#CableCar','#PhotoSpot','#OceanView','#PaidAttraction'],
    true, true, false, 'manual', '₩17,000', NULL,
    'https://en.busanaircruise.co.kr',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Busan Port North Harbor Promenade', 'Walking Trail', 'Dong-gu',
    'Busan Port North Harbor, Dong-gu, Busan',
    'A redeveloped waterfront promenade near Busan Station and the harbor',
    'Future facing waterfront content for arrival day and hotel area itineraries',
    'https://source.unsplash.com/1200x800/?busan,harbor,promenade',
    'https://www.google.com/maps/search/?api=1&query=Busan+North+Port+Promenade',
    'https://map.naver.com/p/search/Busan%20North%20Port%20Promenade',
    35.1132, 129.0474, 60, 'evening', NULL,
    ARRAY['#Waterfront','#Walking','#BusanStation','#Harbor'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Magnate Cafe BTS Jimin Family Area', 'Cafe', 'Suyeong-gu',
    '135 Jinnam-ro, Nam-gu, Busan',
    'A cafe known among BTS fans because of its connection to Jimin''s family',
    'High ARMY travel interest and strong affiliate route potential',
    'https://source.unsplash.com/1200x800/?korea,cafe,bts',
    'https://www.google.com/maps/search/?api=1&query=MAGNATE+Cafe+Busan',
    'https://map.naver.com/p/search/MAGNATE%20Cafe%20Busan',
    35.1385, 129.0847, 60, 'afternoon',
    '{"open":"10:00","close":"21:00"}'::jsonb,
    ARRAY['#BTS','#Cafe','#ARMY','#FanRoute'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.visitbusan.net/en/index.do',
    'https://www.klook.com/en-US/city/79-busan-things-to-do/', 'klook'
  ),
  (
    'busan', 'Busan Asiad Main Stadium', 'Landmark', 'Yeonje-gu',
    '344 World Cup-daero, Yeonje-gu, Busan',
    'A major stadium used for sports concerts and large events',
    'Important event anchor for BTS and K-pop traffic routing',
    'https://source.unsplash.com/1200x800/?stadium,busan',
    'https://www.google.com/maps/search/?api=1&query=Busan+Asiad+Main+Stadium',
    'https://map.naver.com/p/search/Busan%20Asiad%20Main%20Stadium',
    35.1901, 129.0587, 60, 'event', NULL,
    ARRAY['#Stadium','#Kpop','#Event','#Transit'],
    true, true, false, 'manual', 'Free', NULL,
    'https://www.busan.go.kr',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  ),
  (
    'busan', 'Busan Children''s Grand Park', 'Park', 'Busanjin-gu',
    '295 Saessak-ro, Busanjin-gu, Busan',
    'A large family park beside Seongjigok Reservoir and forest trails',
    'Good family and easy nature content near central Busan',
    'https://source.unsplash.com/1200x800/?korea,family,park',
    'https://www.google.com/maps/search/?api=1&query=Busan+Children%27s+Grand+Park',
    'https://map.naver.com/p/search/Busan%20Children%27s%20Grand%20Park',
    35.1838, 129.0458, 120, 'morning',
    '{"open":"05:00","close":"22:00"}'::jsonb,
    ARRAY['#Park','#Family','#Forest','#Walking'],
    true, true, false, 'manual', 'Free', 'easy',
    'https://www.visitbusan.net/en/index.do',
    'https://www.booking.com/searchresults.html?ss=Busan&group_adults=1', 'booking'
  )
ON CONFLICT (city, name) DO NOTHING;

SELECT city, COUNT(*) FROM city_spots GROUP BY city ORDER BY city;
SELECT source_type, COUNT(*) FROM city_spots GROUP BY source_type ORDER BY source_type;
SELECT affiliate_provider, COUNT(*) FROM city_spots GROUP BY affiliate_provider ORDER BY affiliate_provider;

COMMIT;
