import Link from "next/link";

export const metadata = {
  title: "About KoreaMate - KoreaMate",
  description: "Learn about the mission, data sources, and AI technologies powering KoreaMate.",
};

export default function AboutPage() {
  return (
    <div className="min-h-screen flex flex-col bg-[#FAF7F2] text-[#2C2520] font-sans antialiased">
      {/* Navigation Header */}
      <header className="border-b border-[#E6DFD5] bg-[#FAF7F2]/90 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Link href="/" className="text-2xl font-black tracking-tight text-[#2C2520] flex items-center gap-1.5">
              <span className="text-[#D4AF37] text-3xl">🇰🇷</span> Korea<span className="text-[#D4AF37]">Mate</span>
            </Link>
          </div>
          <nav className="flex items-center gap-8">
            <Link
              href="/blog"
              className="text-base font-bold hover:text-[#D4AF37] transition-colors"
            >
              Blog
            </Link>
            <Link
              href="/survival-guide"
              className="text-base font-bold hover:text-[#D4AF37] transition-colors"
            >
              Survival Guide
            </Link>
            <Link
              href="/about"
              className="text-base font-bold text-[#D4AF37] transition-colors"
            >
              About
            </Link>
          </nav>
        </div>
      </header>

      {/* Hero Header */}
      <section className="bg-gradient-to-b from-[#F3EEE3] to-[#FAF7F2] border-b border-[#E6DFD5] py-20 text-center">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <h1 className="text-4xl sm:text-6xl font-black text-[#2C2520] tracking-tight leading-tight">
            About KoreaMate
          </h1>
          <p className="mt-5 text-xl sm:text-2xl text-[#61554D] font-bold">
            Empowering foreign independent travelers to explore Korea worry-free
          </p>
        </div>
      </section>

      {/* Main Content */}
      <main className="max-w-3xl mx-auto w-full px-4 sm:px-6 py-20 flex-1 space-y-12">
        <div className="bg-white rounded-3xl border border-[#E6DFD5] p-8 sm:p-12 shadow-sm space-y-10">
          
          {/* Section 1 - Mission */}
          <section className="space-y-4">
            <h2 className="text-2xl font-black text-[#2C2520] flex items-center gap-2">
              🎯 Our Mission
            </h2>
            <p className="text-lg text-[#61554D] leading-relaxed">
              KoreaMate is an AI-powered travel guide designed specifically for foreign travelers visiting Korea. We help you plan your trip, find solo-friendly spots, and navigate Korea without getting stuck.
            </p>
          </section>

          <hr className="border-[#FAF7F2]" />

          {/* Section 2 - Data Source Attribution */}
          <section className="space-y-4">
            <h2 className="text-2xl font-black text-[#2C2520] flex items-center gap-2">
              📊 Data Sources
            </h2>
            <p className="text-lg text-[#61554D] leading-relaxed">
              Local information is provided by the Korea Tourism Organization (
              <a
                href="https://visitkorea.or.kr"
                target="_blank"
                rel="noopener noreferrer"
                className="font-bold underline hover:text-[#D4AF37]"
              >
                visitkorea.or.kr
              </a>
              ) through their TourAPI. We verify and curate locations to make sure accessibility features, payment guidelines, and solo-friendly attributes are completely transparent.
            </p>
          </section>

          <hr className="border-[#FAF7F2]" />

          {/* Section 3 - AI usage disclosure */}
          <section className="space-y-4">
            <h2 className="text-2xl font-black text-[#2C2520] flex items-center gap-2">
              🤖 AI Technology
            </h2>
            <p className="text-lg text-[#61554D] leading-relaxed">
              Itineraries and blog posts are generated by Gemini AI. While our system is designed to provide highly accurate, optimized, and localized guidance, please verify important details before your trip as local operations can change.
            </p>
          </section>

          <hr className="border-[#FAF7F2]" />

          {/* Section 4 - Contact */}
          <section className="space-y-4">
            <h2 className="text-2xl font-black text-[#2C2520] flex items-center gap-2">
              ✉️ Contact Us
            </h2>
            <p className="text-lg text-[#61554D] leading-relaxed">
              Have feedback or suggestions? We'd love to hear from you. Feel free to contact our team to share your thoughts or report details that need updates. Together, let's make traveling in Korea an unforgettable experience!
            </p>
          </section>

          <hr className="border-[#FAF7F2]" />

          <p className="text-sm text-[#8C6239]">Last updated: 2026-05-31</p>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-[#E6DFD5] bg-[#FAF7F2] py-8 text-center text-sm text-[#8C6239] px-4">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <p>© {new Date().getFullYear()} KoreaMate. All rights reserved.</p>
          <p className="font-bold tracking-wide">
            Data provided by Korea Tourism Organization. AI-powered by Gemini.
          </p>
        </div>
      </footer>
    </div>
  );
}
