import { NextResponse } from "next/server";

// 완전 멱등 마이그레이션: DROP TABLE 없음 — 기존 데이터 보존, 재실행 안전
const MIGRATION_SQL = `
-- ① spots 테이블 (IF NOT EXISTS: 기존 데이터 보존)
CREATE TABLE IF NOT EXISTS spots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description TEXT,
    image_url TEXT,
    difficulty VARCHAR(50),
    duration_min INT,
    required_gear TEXT,
    affiliate_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_spots_place_id ON spots(place_id);
CREATE INDEX IF NOT EXISTS idx_spots_category ON spots(category);
ALTER TABLE spots ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_all" ON spots;
CREATE POLICY "anon_all" ON spots FOR ALL TO anon USING (true) WITH CHECK (true);

-- ② spot_reactions 테이블
CREATE TABLE IF NOT EXISTS spot_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id VARCHAR(255) NOT NULL,
  reaction VARCHAR(20) NOT NULL DEFAULT 'dislike',
  device_id VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_spot_reactions_place_id ON spot_reactions(place_id);
ALTER TABLE spot_reactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_insert_reactions" ON spot_reactions;
CREATE POLICY "anon_insert_reactions" ON spot_reactions FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS "anon_read_reactions" ON spot_reactions;
CREATE POLICY "anon_read_reactions" ON spot_reactions FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "anon_delete_reactions" ON spot_reactions;
CREATE POLICY "anon_delete_reactions" ON spot_reactions FOR DELETE TO anon USING (true);

-- ③ 안전 스키마 추가: itineraries 커스텀 제목 컬럼
ALTER TABLE itineraries ADD COLUMN IF NOT EXISTS trip_title TEXT;

-- ④ 이메일 캡처: itineraries에 email 컬럼 추가 (비회원 이메일 저장용)
ALTER TABLE itineraries ADD COLUMN IF NOT EXISTS email TEXT;
CREATE INDEX IF NOT EXISTS idx_itineraries_email ON itineraries(email);

-- ⑤ user_emails: 이메일 ↔ device_id 매핑 테이블 (비회원 전환 흐름의 핵심)
CREATE TABLE IF NOT EXISTS user_emails (
  id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  email      TEXT NOT NULL,
  device_id  TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(email, device_id)
);
CREATE INDEX IF NOT EXISTS idx_user_emails_email  ON user_emails(email);
CREATE INDEX IF NOT EXISTS idx_user_emails_device ON user_emails(device_id);
ALTER TABLE user_emails ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_insert_emails" ON user_emails;
CREATE POLICY "anon_insert_emails" ON user_emails FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS "anon_read_own_emails" ON user_emails;
CREATE POLICY "anon_read_own_emails" ON user_emails FOR SELECT TO anon USING (true);
`.trim();

export async function POST(request: Request) {
  const body = await request.json().catch(() => ({})) as Record<string, string>;
  const adminKey = process.env.NEXT_PUBLIC_ADMIN_KEY ?? "km-admin-2026";
  if (body.key !== adminKey) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const accessToken = process.env.SUPABASE_ACCESS_TOKEN;

  if (!supabaseUrl) {
    return NextResponse.json(
      { error: "NEXT_PUBLIC_SUPABASE_URL 환경변수가 없습니다." },
      { status: 500 }
    );
  }

  if (!accessToken) {
    return NextResponse.json(
      {
        error: "TOKEN_MISSING",
        message:
          "SUPABASE_ACCESS_TOKEN이 .env.local에 없습니다. " +
          "https://supabase.com/dashboard/account/tokens 에서 토큰 생성 후 추가하세요.",
      },
      { status: 503 }
    );
  }

  // URL 형식: https://[ref].supabase.co
  const projectRef = supabaseUrl.replace("https://", "").split(".")[0];

  const res = await fetch(
    `https://api.supabase.com/v1/projects/${projectRef}/database/query`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query: MIGRATION_SQL }),
    }
  ).catch((err: Error) => {
    throw new Error(`네트워크 오류: ${err.message}`);
  });

  const data = await res.json().catch(() => null);

  if (!res.ok) {
    return NextResponse.json(
      { error: (data as { message?: string })?.message ?? `HTTP ${res.status}`, details: data },
      { status: 500 }
    );
  }

  return NextResponse.json({ success: true, message: "마이그레이션 완료 (spots + spot_reactions + itineraries.trip_title + user_emails + itineraries.email)" });
}
