import { NextResponse } from "next/server";

// supabase/migrations/001_spots_table.sql 와 동일 내용 (서버에서 자동 실행)
const MIGRATION_SQL = `
DROP TABLE IF EXISTS spots CASCADE;
CREATE TABLE spots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description TEXT,
    image_url TEXT,
    difficulty VARCHAR(50),
    duration_min INT,
    required_gear TEXT,
    affiliate_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_spots_place_id ON spots(place_id);
CREATE INDEX idx_spots_category ON spots(category);
ALTER TABLE spots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_all" ON spots FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS spot_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id VARCHAR(255) NOT NULL,
  reaction VARCHAR(20) NOT NULL DEFAULT 'dislike',
  device_id VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_spot_reactions_place_id ON spot_reactions(place_id);
ALTER TABLE spot_reactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_insert_reactions" ON spot_reactions;
CREATE POLICY "anon_insert_reactions" ON spot_reactions FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS "anon_read_reactions" ON spot_reactions;
CREATE POLICY "anon_read_reactions" ON spot_reactions FOR SELECT TO anon USING (true);
`.trim();

export async function POST(request: Request) {
  const body = await request.json().catch(() => ({})) as Record<string, string>;
  const adminKey = process.env.NEXT_PUBLIC_ADMIN_KEY ?? "km-admin-2026";
  if (body.key !== adminKey) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const accessToken = process.env.SUPABASE_ACCESS_TOKEN;

  if (!supabaseUrl) {
    return NextResponse.json(
      { error: "NEXT_PUBLIC_SUPABASE_URL 환경변수가 없습니다." },
      { status: 500 }
    );
  }

  if (!accessToken) {
    return NextResponse.json(
      {
        error: "TOKEN_MISSING",
        message:
          "SUPABASE_ACCESS_TOKEN이 .env.local에 없습니다. " +
          "https://supabase.com/dashboard/account/tokens 에서 토큰 생성 후 추가하세요.",
      },
      { status: 503 }
    );
  }

  // URL 형식: https://[ref].supabase.co
  const projectRef = supabaseUrl.replace("https://", "").split(".")[0];

  const res = await fetch(
    `https://api.supabase.com/v1/projects/${projectRef}/database/query`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query: MIGRATION_SQL }),
    }
  ).catch((err: Error) => {
    throw new Error(`네트워크 오류: ${err.message}`);
  });

  const data = await res.json().catch(() => null);

  if (!res.ok) {
    return NextResponse.json(
      { error: (data as { message?: string })?.message ?? `HTTP ${res.status}`, details: data },
      { status: 500 }
    );
  }

  return NextResponse.json({ success: true, message: "spots 테이블 생성 완료" });
}
