DROP TABLE IF EXISTS spots CASCADE;
CREATE TABLE spots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description TEXT,
    image_url TEXT,
    difficulty VARCHAR(50),
    duration_min INT,
    required_gear TEXT,
    affiliate_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_spots_place_id ON spots(place_id);
CREATE INDEX idx_spots_category ON spots(category);
ALTER TABLE spots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_all" ON spots FOR ALL TO anon USING (true) WITH CHECK (true);

-- spot_reactions: 유저 피드백/신뢰도 검증 테이블
CREATE TABLE IF NOT EXISTS spot_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id VARCHAR(255) NOT NULL,
  reaction VARCHAR(20) NOT NULL DEFAULT 'dislike',
  device_id VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_spot_reactions_place_id ON spot_reactions(place_id);
ALTER TABLE spot_reactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_insert_reactions" ON spot_reactions;
CREATE POLICY "anon_insert_reactions" ON spot_reactions FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS "anon_read_reactions" ON spot_reactions;
CREATE POLICY "anon_read_reactions" ON spot_reactions FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "anon_delete_reactions" ON spot_reactions;
CREATE POLICY "anon_delete_reactions" ON spot_reactions FOR DELETE TO anon USING (true);
