DROP TABLE IF EXISTS spots CASCADE;
CREATE TABLE spots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description TEXT,
    image_url TEXT,
    difficulty VARCHAR(50),
    duration_min INT,
    required_gear TEXT,
    affiliate_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_spots_place_id ON spots(place_id);
CREATE INDEX idx_spots_category ON spots(category);
ALTER TABLE spots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_all" ON spots FOR ALL TO anon USING (true) WITH CHECK (true);
