-- 012_city_spots.sql
-- ExploreCity용 스팟 데이터 테이블
-- 기존 spots 테이블(하이킹 전용)과 별도 — 충돌 없음

CREATE TABLE IF NOT EXISTS city_spots (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city                 TEXT        NOT NULL,
  name                 TEXT        NOT NULL,
  name_l10n            JSONB,                         -- {en, ko, ja, zh}
  category             TEXT        NOT NULL,           -- attraction|restaurant|nature|event|accommodation
  district             TEXT,
  address              TEXT,
  description          TEXT,
  desc_l10n            JSONB,                         -- {en, ko, ja, zh}
  why_it_matters       TEXT,
  why_l10n             JSONB,                         -- {en, ko, ja, zh}
  image_url            TEXT,
  map_url              TEXT,
  naver_map_url        TEXT,
  lat                  DOUBLE PRECISION,
  lng                  DOUBLE PRECISION,
  duration_minutes     INT,
  best_time_slot       TEXT,
  opening_hours        JSONB,                         -- {open, close} | null
  tags                 TEXT[],
  solo_friendly        BOOLEAN     NOT NULL DEFAULT true,
  foreign_card_accepted BOOLEAN    NOT NULL DEFAULT true,
  cash_only            BOOLEAN     NOT NULL DEFAULT false,
  -- 외부 API 소스 (TourAPI / Google Places 1회 import 후 캐싱)
  source_type          TEXT        NOT NULL DEFAULT 'manual', -- manual|tourapi|google
  external_id          TEXT,                          -- TourAPI contentId | Google place_id
  rating               NUMERIC(3,1),                 -- Google Places 별점 (cached)
  -- 비즈니스 퍼널 (공식 정보 → 숙박 수익화)
  official_url         TEXT,                          -- 공식 공원/산 관리 사이트
  affiliate_url        TEXT,                          -- 숙박/투어 제휴 링크
  affiliate_provider   VARCHAR(50),                   -- 'agoda'|'booking'|'klook' 등
  -- 외국인 핵심 기초정보 (입력 후 거의 불변)
  entry_fee            VARCHAR(50),                   -- '무료'|'₩2,000'|'Free'
  difficulty           VARCHAR(20),                   -- 'easy'|'moderate'|'hard' (하이킹만)
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- source_type+external_id 중복 방지 (NULL external_id 제외)
CREATE UNIQUE INDEX IF NOT EXISTS idx_city_spots_source_external
  ON city_spots(source_type, external_id)
  WHERE external_id IS NOT NULL;

-- 조회 최적화 인덱스
CREATE INDEX IF NOT EXISTS idx_city_spots_city          ON city_spots(city);
CREATE INDEX IF NOT EXISTS idx_city_spots_category      ON city_spots(category);
CREATE INDEX IF NOT EXISTS idx_city_spots_city_category ON city_spots(city, category);
CREATE INDEX IF NOT EXISTS idx_city_spots_latlon
  ON city_spots(lat, lng)
  WHERE lat IS NOT NULL AND lng IS NOT NULL;

-- RLS: 누구나 읽기 가능, 쓰기는 서비스 키만
ALTER TABLE city_spots ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_read_city_spots" ON city_spots;
CREATE POLICY "anon_read_city_spots" ON city_spots FOR SELECT TO anon USING (true);

-- ── Seed: 부산 초기 7개 스팟 ──────────────────────────────────
INSERT INTO city_spots
  (city, name, category, district, address, description, why_it_matters,
   image_url, map_url, naver_map_url, lat, lng,
   duration_minutes, best_time_slot, opening_hours, tags,
   solo_friendly, foreign_card_accepted, cash_only, source_type,
   entry_fee, difficulty, official_url)
VALUES
(
  'Busan', 'Haeundae Beach', 'attraction', 'Haeundae-gu',
  'Haeundae-gu, Busan — Nearest subway: Haeundae Station (Line 2, Exit 3/5)',
  'A 1.8km white-sand stretch in Haeundae-gu, open year-round. Street food stalls line the beachfront (tteokbokki, sundae, fish cake). The stretch from Haeundae to Dalmaji Hill offers a quieter, scenic walk. Sunrise views from the east end are exceptional. Free entry. Foreign cards accepted at most cafés and restaurants nearby.',
  'Korea''s most iconic beach — the undisputed starting point of every Busan trip.',
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600',
  'https://maps.google.com/?q=Haeundae+Beach+Busan',
  'https://map.naver.com/v5/search/%ED%95%B4%EC%9A%B4%EB%8C%80%ED%95%B4%EC%88%98%EC%9A%95%EC%9E%A5',
  35.1587, 129.1604, 120, 'afternoon', NULL,
  ARRAY['#Beach','#Summer','#Seafood','#Sunrise','#PhotoSpot'],
  true, true, false, 'manual',
  'Free', NULL, NULL
),
(
  'Busan', 'Gamcheon Culture Village', 'attraction', 'Saha-gu',
  'Gamcheon 2-dong, Saha-gu, Busan — Bus 1-1 or 2 from Toseong-dong terminal',
  'A hillside maze of pastel houses, murals, and art installations built on a steep slope in Saha-gu. Open 09:00–18:00 daily (closed some Mondays). Entry map available at the visitor center for ₩2,000 (redeemable as café stamp). Wear comfortable shoes — the alleys are steep and uneven. No large vehicles; arrive by bus or taxi. Foreign cards accepted at the souvenir shops.',
  'The most photogenic neighborhood in Busan — every painted staircase and alley is a photo opportunity.',
  'https://images.unsplash.com/photo-1548115184-bc6544d06a58?w=600',
  'https://maps.google.com/?q=Gamcheon+Culture+Village+Busan',
  'https://map.naver.com/v5/search/%EA%B0%90%EC%B2%9C%EB%AC%B8%ED%99%94%EB%A7%88%EC%9D%84',
  35.0975, 129.0104, 90, 'morning', '{"open":"09:00","close":"18:00"}',
  ARRAY['#ColorfulVillage','#Art','#Mural','#PhotoSpot','#BTS'],
  true, true, false, 'manual',
  '₩2,000', NULL, NULL
),
(
  'Busan', 'Jagalchi Fish Market', 'restaurant', 'Jung-gu',
  '52 Jagalchihaean-ro, Jung-gu, Busan — Jagalchi Station (Line 1, Exit 10)',
  'Korea''s largest seafood market, open since 1971. Ground floor vendors sell live fish, abalone, crab, and shellfish. Take your pick upstairs to a cooking booth — they''ll prepare it in minutes. Solo dining is completely normal; just point at what you want. Open 07:00–21:00 daily. Mostly cash only; bring ₩20,000–₩40,000 for a full solo meal. The market is a 2-min walk from Jagalchi subway station.',
  'The freshest seafood in Korea, cooked to order — this is the unmistakable taste of Busan.',
  'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=600',
  'https://maps.google.com/?q=Jagalchi+Fish+Market+Busan',
  'https://map.naver.com/v5/search/%EC%9E%90%EA%B0%88%EC%B9%98%EC%8B%9C%EC%9E%A5',
  35.0971, 129.0302, 60, 'morning', '{"open":"07:00","close":"21:00"}',
  ARRAY['#Seafood','#FishMarket','#LocalFood','#SoloFriendly','#CashOnly'],
  true, false, true, 'manual',
  'Free entry', NULL, NULL
),
(
  'Busan', 'Gwangalli Beach & Bridge', 'attraction', 'Suyeong-gu',
  'Gwangalli 1-dong, Suyeong-gu, Busan — Gwangan Station (Line 2, Exit 3) or Geumnyeonsan Station (Exit 7)',
  'A 1.4km sandy beach lined with independent cafés, bars, and seafood restaurants — hipper and less crowded than Haeundae. The landmark Gwangan Bridge (광안대교) stretches 7.4km across the bay and lights up nightly. Arrive at sunset and stay through the bridge lighting (around 20:00). Foreign cards accepted everywhere along the strip. The beach itself is free; parking is limited, so the subway is recommended.',
  'Busan''s trendiest beachfront — best at night when Gwangan Bridge illuminates the entire bay.',
  'https://images.unsplash.com/photo-1583689397935-7de22f67e3c7?w=600',
  'https://maps.google.com/?q=Gwangalli+Beach+Busan',
  'https://map.naver.com/v5/search/%EA%B4%91%EC%95%88%EB%A6%AC%ED%95%B4%EC%88%98%EC%9A%95%EC%9E%A5',
  35.1530, 129.1185, 90, 'evening', NULL,
  ARRAY['#Beach','#GwanganBridge','#NightView','#Seafood','#PhotoSpot'],
  true, true, false, 'manual',
  'Free', NULL, NULL
),
(
  'Busan', 'Hwangnyeongsan Night View Trail', 'nature', 'Yeonje-gu',
  'Hwangnyeong-dong, Yeonje-gu, Busan — Bus 41 or 42 to Hwangnyeongsan trailhead',
  'Hwangnyeongsan (황령산, 427m) sits at the geographic center of Busan, offering unobstructed 360° views of the city, Gwangalli Bridge, and the ocean. The summit is reached in about 40 minutes via the main trail. Go after 19:00 for the city-light panorama. Wear non-slip shoes; the trail is rocky after rain. Free entry, no facilities at the top — bring water. Bus 41 or 42 from Yeonsan-dong stops at the trailhead. No subway access; a taxi (₩5,000–₩8,000) is easiest.',
  'Busan''s best free experience — a 40-min hike to a 360° city panorama consistently ranked #1 by foreign visitors.',
  'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=600',
  'https://maps.google.com/?q=%ED%99%A9%EB%A0%B9%EC%82%B0+%EB%B6%80%EC%82%B0',
  'https://map.naver.com/v5/search/%ED%99%A9%EB%A0%B9%EC%82%B0',
  35.1475, 129.0715, 120, 'evening', NULL,
  ARRAY['#NightView','#Hiking','#PhotoSpot','#Busan','#Free'],
  true, false, false, 'manual',
  'Free', 'moderate', 'https://www.busan.go.kr/yeonje/hwangnyeong'
),
(
  'Busan', 'Jangsan Mountain Trail', 'nature', 'Haeundae-gu',
  'Jangsan, Haeundae-gu, Busan — Jangsan Station (Line 2, Exit 7) → 15-min walk to trailhead',
  'Jangsan (장산, 634m) is the highest peak in Haeundae-gu. Multiple trails range from easy valley walks (1hr round trip) to full summit routes (3hr). The valley path features small waterfalls and pine-scented air. The summit offers partial views of the East Sea on clear days. Free entry. Take Line 2 to Jangsan Station (Exit 7) and walk 15 minutes uphill to the main entrance. Bring water; no refreshment stands on the trail. Suitable for solo hikers — the trail is well-marked in Korean and partially in English.',
  'Haeundae''s hidden green lung — forest trails and streams just 15 minutes from the beach.',
  'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600',
  'https://maps.google.com/?q=%EC%9E%A5%EC%82%B0+%ED%95%B4%EC%9A%B4%EB%8C%80%EA%B5%AC+%EB%B6%80%EC%82%B0',
  'https://map.naver.com/v5/search/%EC%9E%A5%EC%82%B0%EB%93%B1%EC%82%B0%EB%A1%9C',
  35.1894, 129.2017, 180, 'morning', NULL,
  ARRAY['#Hiking','#Forest','#Stream','#Haeundae','#Free'],
  true, false, false, 'manual',
  'Free', 'moderate', 'https://haeundae.go.kr/jangsanlocalpark/index.do'
),
(
  'Busan', 'Igidae Coastal Walk', 'nature', 'Nam-gu',
  'Igidae Park entrance: 116 Igidae-ro, Nam-gu, Busan — Bus 27 or 131 to Igidae Park stop',
  'Igidae (이기대) is a 4.7km coastal cliff trail in Nam-gu connecting Oryukdo Skywalk to Gwangalli Beach. The path runs along the edge of sheer sea cliffs with views across the bay toward Haeundae. Highlights include sea caves, tidal pools, and wildflowers (spring). Difficulty: easy-moderate. The trail is paved in sections and has wooden boardwalks along the cliff edges. Entrance near Oryukdo Skywalk: Bus 27 or 131 from Gwangalli or Namcheon Station. Free entry. Bring water — no vending facilities on the trail. Allow 2.5–3 hours for the full route.',
  'The most dramatic free coastal trail in Korea — 5km of sea cliffs, caves, and crashing waves.',
  'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600',
  'https://maps.google.com/?q=%EC%9D%B4%EA%B8%B0%EB%8C%80%ED%95%B4%EC%95%88%EC%82%B0%EC%B1%85%EB%A1%9C+%EB%B6%80%EC%82%B0',
  'https://map.naver.com/v5/search/%EC%9D%B4%EA%B8%B0%EB%8C%80%ED%95%B4%EC%95%88%EC%82%B0%EC%B1%85%EB%A1%9C',
  35.1215, 129.1287, 150, 'afternoon', NULL,
  ARRAY['#CoastalWalk','#Cliffs','#OceanView','#Free','#Oryukdo'],
  true, false, false, 'manual',
  'Free', 'easy', 'https://www.namgu.busan.kr/'
)
ON CONFLICT DO NOTHING;
