-- 020: itinerary_helpful_votes dedup 테이블 + 원자적 RPC
-- 배포 순서: 020 migration 적용 → 코드 배포 → smoke test → 021 migration 적용
-- 기존 increment_trip_helpful anon EXECUTE는 이 파일에서 유지 (021에서 차단)

BEGIN;

-- ── dedup 테이블 ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.itinerary_helpful_votes (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itinerary_id   UUID        NOT NULL,
  device_id      TEXT        NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_ihv_itinerary_device UNIQUE (itinerary_id, device_id)
);

CREATE INDEX IF NOT EXISTS idx_ihv_itinerary_id ON public.itinerary_helpful_votes(itinerary_id);

ALTER TABLE public.itinerary_helpful_votes ENABLE ROW LEVEL SECURITY;
-- anon/authenticated 직접 접근 없음. service_role 경유 RPC 전용.

-- ── 원자적 RPC ────────────────────────────────────────────────────────────────
-- INSERT vote + helpful_count 증가를 단일 트랜잭션 내에서 처리
-- 중복 device_id: INSERT ON CONFLICT DO NOTHING → count 증가 없이 현재값 반환
-- 반환: added=true(신규 투표), false(중복); helpful_count=최신 카운트
CREATE OR REPLACE FUNCTION public.add_itinerary_helpful_vote(
  p_itinerary_id UUID,
  p_device_id    TEXT
)
RETURNS TABLE (added BOOLEAN, helpful_count INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_rows          BIGINT  := 0;
  v_added         BOOLEAN := false;
  v_helpful_count INTEGER;
BEGIN
  IF p_itinerary_id IS NULL OR p_device_id IS NULL OR length(p_device_id) = 0 THEN
    RETURN;
  END IF;

  INSERT INTO public.itinerary_helpful_votes(itinerary_id, device_id)
  VALUES (p_itinerary_id, p_device_id)
  ON CONFLICT (itinerary_id, device_id) DO NOTHING;

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  v_added := (v_rows > 0);

  IF v_added THEN
    UPDATE public.itineraries
    SET helpful_count = helpful_count + 1
    WHERE id = p_itinerary_id
    RETURNING helpful_count INTO v_helpful_count;
  ELSE
    SELECT i.helpful_count INTO v_helpful_count
    FROM public.itineraries i
    WHERE i.id = p_itinerary_id;
  END IF;

  RETURN QUERY SELECT v_added, COALESCE(v_helpful_count, 0);
END;
$$;

REVOKE ALL     ON FUNCTION public.add_itinerary_helpful_vote(UUID, TEXT) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.add_itinerary_helpful_vote(UUID, TEXT) TO service_role;

COMMIT;
