-- 082: 문의·신고 기록 일일 파기 (LEGAL-RETENTION-IMPLEMENTATION-V1)
--
-- Owner 선택(2026-09-28) — 법정 기간이 아니라 사업자 운영 기준이다:
--   · 신고(place_reports): 처리 완료(resolved_at) 후 6개월이 지나면 파기.
--     처리 중(pending·reviewing)인 신고는 파기하지 않고, 30일 넘게 처리 중이면
--     실행 원장에 세어 주 1회 알림 대상으로 올린다(무기한 방치 방지).
--   · 문의(contact_inquiries): 접수(created_at) 후 6개월이 지나면 파기.
--     진행 중이라 기한을 넘겨야 하는 문의만 예외 — 사유·책임자·검토일을 적은
--     retention_hold_* 가 있고 검토일이 아직 지나지 않은 동안만 보류한다.
--     검토일이 지나면 예외가 끝나 다음 실행에서 일반 기준으로 파기된다.
--
-- 실행 구조(076 과 같은 pg_cron 방식):
--   · 매일 KST 03:27(UTC 18:27) retention_purge_daily() 1회.
--   · advisory lock — 동시·중복 실행이 겹치지 않는다. 같은 날 다시 돌려도
--     이미 지운 행은 대상이 아니라 결과가 같다(멱등).
--   · 대상 수를 먼저 세고 지운 뒤 두 수를 원장에 남긴다. 원장에는 건수·상태·
--     오류 코드만 있다 — 이메일·메시지·메모·신고 키 등 원문은 남기지 않는다.
--   · 실패하면 그 회차의 삭제는 전부 되돌려지고(블록 롤백) 원장에 failed 가
--     남으며 알림을 보낸다. 다음 날 실행이 자동 재시도다.
--   · 알림: pg_net 으로 사이트의 /api/internal/retention-alert 를 호출한다.
--     URL·내부 키는 Vault(retention_alert_url·retention_alert_key)에서 읽는다 —
--     비어 있으면 알림만 건너뛰고 원장에 그 사실을 남긴다(파기는 계속).
--
-- 권한: 함수는 SECURITY DEFINER + search_path 고정, anon·authenticated 실행 불가.
-- 원장·예외 컬럼은 RLS 로 브라우저 접근을 막는다(서버 service_role 전용).
-- 의존: place_reports(042)·contact_inquiries(선재)·pg_cron(076). 077~081 과 무관.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

-- ── 문의 보관 예외(진행 중 문의만) ────────────────────────────────────────
ALTER TABLE public.contact_inquiries
  ADD COLUMN IF NOT EXISTS retention_hold_until  DATE,
  ADD COLUMN IF NOT EXISTS retention_hold_reason TEXT CHECK (retention_hold_reason IS NULL OR char_length(retention_hold_reason) BETWEEN 5 AND 500),
  ADD COLUMN IF NOT EXISTS retention_hold_by     TEXT CHECK (retention_hold_by IS NULL OR char_length(retention_hold_by) BETWEEN 1 AND 100);

-- ── 실행 원장(원문 없음) ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.retention_purge_runs (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  status              TEXT        NOT NULL CHECK (status IN ('ok', 'failed')),
  reports_eligible    INTEGER     NOT NULL DEFAULT 0,
  reports_deleted     INTEGER     NOT NULL DEFAULT 0,
  reports_stale_open  INTEGER     NOT NULL DEFAULT 0,
  inquiries_eligible  INTEGER     NOT NULL DEFAULT 0,
  inquiries_deleted   INTEGER     NOT NULL DEFAULT 0,
  inquiries_held      INTEGER     NOT NULL DEFAULT 0,
  error_code          TEXT,
  alert               TEXT        NOT NULL DEFAULT 'none' CHECK (alert IN ('none', 'sent', 'skipped_no_config'))
);
ALTER TABLE public.retention_purge_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.retention_purge_runs FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.retention_purge_runs TO service_role;

-- ── 알림(내부 전용) ───────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.retention_purge_alert(p_kind TEXT, p_payload JSONB)
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_url TEXT;
  v_key TEXT;
BEGIN
  SELECT decrypted_secret INTO v_url FROM vault.decrypted_secrets WHERE name = 'retention_alert_url' LIMIT 1;
  SELECT decrypted_secret INTO v_key FROM vault.decrypted_secrets WHERE name = 'retention_alert_key' LIMIT 1;
  IF v_url IS NULL OR v_key IS NULL THEN
    RETURN 'skipped_no_config';
  END IF;
  PERFORM net.http_post(
    url     := v_url,
    headers := jsonb_build_object('content-type', 'application/json', 'x-internal-auth', v_key),
    body    := jsonb_build_object('kind', p_kind) || p_payload
  );
  RETURN 'sent';
END $$;

REVOKE ALL ON FUNCTION public.retention_purge_alert(TEXT, JSONB) FROM PUBLIC, anon, authenticated;

-- ── 일일 파기 ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.retention_purge_daily()
RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_rep_eligible INTEGER := 0;
  v_rep_deleted  INTEGER := 0;
  v_rep_stale    INTEGER := 0;
  v_inq_eligible INTEGER := 0;
  v_inq_deleted  INTEGER := 0;
  v_inq_held     INTEGER := 0;
  v_status       TEXT := 'ok';
  v_error        TEXT;
  v_alert        TEXT := 'none';
  v_run_id       BIGINT;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('retention_purge_daily'));

  BEGIN
    -- 신고: 처리 완료 + 6개월
    SELECT count(*) INTO v_rep_eligible FROM public.place_reports
     WHERE status IN ('resolved_corrected','resolved_no_change','resolved_hidden','resolved_removed','rejected','duplicate')
       AND resolved_at IS NOT NULL
       AND resolved_at <= now() - interval '6 months';
    WITH d AS (
      DELETE FROM public.place_reports
       WHERE status IN ('resolved_corrected','resolved_no_change','resolved_hidden','resolved_removed','rejected','duplicate')
         AND resolved_at IS NOT NULL
         AND resolved_at <= now() - interval '6 months'
      RETURNING 1)
    SELECT count(*) INTO v_rep_deleted FROM d;

    -- 처리 중 30일 초과(파기하지 않음 — 검토 알림용 집계)
    SELECT count(*) INTO v_rep_stale FROM public.place_reports
     WHERE status IN ('pending','reviewing') AND created_at <= now() - interval '30 days';

    -- 문의: 접수 + 6개월, 유효한 예외(검토일 미도래)는 보류
    SELECT count(*) INTO v_inq_held FROM public.contact_inquiries
     WHERE created_at <= now() - interval '6 months'
       AND retention_hold_until IS NOT NULL AND retention_hold_until >= current_date;
    SELECT count(*) INTO v_inq_eligible FROM public.contact_inquiries
     WHERE created_at <= now() - interval '6 months'
       AND (retention_hold_until IS NULL OR retention_hold_until < current_date);
    WITH d AS (
      DELETE FROM public.contact_inquiries
       WHERE created_at <= now() - interval '6 months'
         AND (retention_hold_until IS NULL OR retention_hold_until < current_date)
      RETURNING 1)
    SELECT count(*) INTO v_inq_deleted FROM d;

    IF v_rep_deleted <> v_rep_eligible OR v_inq_deleted <> v_inq_eligible THEN
      RAISE EXCEPTION 'count_mismatch';
    END IF;
  EXCEPTION WHEN OTHERS THEN
    -- 블록 안의 삭제는 모두 롤백된다. 원문 없이 오류 코드만 남긴다.
    v_status := 'failed';
    v_error := SQLSTATE || ':' || left(SQLERRM, 80);
    v_rep_deleted := 0;
    v_inq_deleted := 0;
  END;

  IF v_status = 'failed' THEN
    v_alert := public.retention_purge_alert('failed', jsonb_build_object('error_code', v_error));
  ELSIF v_rep_stale > 0 AND extract(isodow FROM now() AT TIME ZONE 'Asia/Seoul') = 1 THEN
    v_alert := public.retention_purge_alert('stale_open_reports', jsonb_build_object('count', v_rep_stale));
  END IF;

  INSERT INTO public.retention_purge_runs
    (status, reports_eligible, reports_deleted, reports_stale_open,
     inquiries_eligible, inquiries_deleted, inquiries_held, error_code, alert)
  VALUES
    (v_status, v_rep_eligible, v_rep_deleted, v_rep_stale,
     v_inq_eligible, v_inq_deleted, v_inq_held, v_error, v_alert)
  RETURNING id INTO v_run_id;
  RETURN v_run_id;
END $$;

REVOKE ALL ON FUNCTION public.retention_purge_daily() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.retention_purge_daily() TO service_role;

-- ── 스케줄(멱등 등록 — 076 과 같은 방식) ─────────────────────────────────
DO $sched$
DECLARE
  v_id BIGINT;
BEGIN
  -- 매일 KST 03:27 = UTC 18:27
  SELECT jobid INTO v_id FROM cron.job WHERE jobname = 'gokoreamate-retention-purge-daily-v1';
  IF v_id IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM cron.job WHERE jobid = v_id
        AND schedule = '27 18 * * *'
        AND command  = 'SELECT public.retention_purge_daily();') THEN
    PERFORM cron.unschedule(v_id);
    v_id := NULL;
  END IF;
  IF v_id IS NULL THEN
    PERFORM cron.schedule(
      'gokoreamate-retention-purge-daily-v1',
      '27 18 * * *',
      'SELECT public.retention_purge_daily();');
  END IF;
END $sched$;

COMMIT;
